name: Publish to npm

on:
  push:
    branches:
      - main # Publish when changes are pushed to the main branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your Node.js version
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build # Only if you have a build step (e.g., for TypeScript)

      - name: Publish to npm # Correct indentation here
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
